# Generated by Django 5.0.1 on 2024-02-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userregister',
            name='message',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
