# Generated by Django 5.0.1 on 2024-03-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybackend', '0002_userregister_address_userregister_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('comments', models.TextField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='userregister',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='phone',
            field=models.IntegerField(max_length=50),
        ),
    ]
